Testing physics box2d + sfml
PlatformerTeam/mad pull request #15
Opened 2022-02-21 13:03 UTC by Mirong1707

2022-02-21 13:10 UTC, Glebanister requested changes

2022-02-21 13:10 UTC, Glebanister commented on test/test.cpp
> +int main(int argc, char **argv) {
У gtest в main ничего не пишут. Он нужен исключительно для того, чтобы запустить фреймворк для тестов. Если хочется написать какой-то тест

```C++
TEST(Box2dFunctionality, Basic) {
    // ... тут пишем код теста, используя EXPECT_EQ и другую функциональность gtest
}
```

2022-02-21 13:10 UTC, Glebanister commented on test/test.cpp
> +#include <gtest/gtest.h>
В целом, если это просто тестовый файлик, в котором мы не собираемся делать EXPECT_EQ и всё такое, а просто хотим поиграть с возможностями, то можно добавить отдельный исполняемый файл в тесты (add_executable). Потому что мы наверное не хотим запуская тесты увидеть окошко игры, так как там просто будет тестироваться функциональность разных модулей движка

2022-02-22 10:24 UTC, Mirong1707 commented on test/test.cpp
> +#include <gtest/gtest.h>
нужно тогда issue по этому сделать видимо

2022-02-22 12:46 UTC, Glebanister commented on test/test.cpp
> +#include <gtest/gtest.h>
Я пока не буду плодить ишью, сперва закроем #3
Можешь сам исправить там мои замечания вместо Дениса, если есть время

2022-02-22 13:29 UTC, merged