Create StaticImage
PlatformerTeam/mad pull request #66
Opened 2022-03-17 20:56 UTC by Alexeyha

2022-03-17 21:00 UTC, Alexeyha commented
Пока лучшим решением вижу хранение sf::Texture как поле в StaticImage. Проблема в том, что ни sf::Texture, ни sf::Sprite не позволяют хранить себя в указателях. Поэтому пока в конструкторе создаю texture и затем ей приходится копироваться, пока не понятно насколько это плохо, и возможно ли этого избежать.

2022-03-17 22:36 UTC, Glebanister requested changes

2022-03-17 22:36 UTC, Glebanister commented on core/visual/image/static/StaticImage.cpp
> +            FAIL("File does not exist")
Тут должно быть CHECK_THROW

2022-03-17 22:36 UTC, Glebanister commented on core/visual/image/static/StaticImage.cpp
> +            FAIL("File does not exist")
Ну и добавить нужный тип ошибки соответственно

2022-03-17 22:36 UTC, Glebanister commented on core/visual/image/static/StaticImage.hpp
> +#include <common/Error.hpp>
Error нужен только в .cpp

2022-03-17 22:36 UTC, Glebanister commented on core/visual/Camera.cpp
> +        sf::Sprite render_sprite;
Надо поизучать насколько плохо каждую итерацию создавать новый спрайт и текстуру. Почему нельзя хранить где-то спрайты (с уже установленной текстурой) и когда нужно делать у них setPosition?

2022-03-18 12:22 UTC, Alexeyha commented
Себе: подумать, как лучше делать, сначала масштаб, потом align или наоборот.
To reviewers: возможно передавать в конструктор и масштаб и align с дефолтными значениями плохо. Возможно достаточно двух сеттеров (они тоже есть)

2022-03-18 13:47 UTC, Alexeyha commented
Мне не особо нравится название метода, но не придумал лучше( Также пока оставил сеттеры, вдруг пригодятся

2022-03-18 13:59 UTC, Glebanister requested changes

2022-03-18 13:59 UTC, Glebanister commented on core/visual/Camera.hpp
>  #include "event/management/dispatcher/EventDispatcher.hpp"
Стиль кавычек `<>`

2022-03-18 13:59 UTC, Glebanister commented on core/visual/image/static/StaticImage.cpp
> +#include "StaticImage.hpp"
Перенос строки

2022-03-18 13:59 UTC, Glebanister commented on core/visual/image/static/StaticImage.cpp
> +    void StaticImage::set_shape(std::uint32_t width, std::uint32_t height, StaticImage::TransformType transform_type) {
Нужна проверка `CHECK_THROW` на ненулевые width, height

2022-03-18 14:10 UTC, merged